### ISSUE TITLE
Not handling properly: channel/connection is not open

### ISSUE THREAD

**Issue by joaoppereira** [krakendio/krakend-amqp#8]
Hi everyone,

We're using KrakenD as our API Gateway and we're using krakend-amqp to directly publish in our RabbitMq cluster and it keeps losing the connection/channel, and it only recovers rebooting KrakenD.

Our configuration:

```
"extra_config": {
          "github.com/devopsfaith/krakend-amqp/produce": {
            "routing_key": "Route",
            "exchange": "search",
            "durable": true,
            "delete": false,
            "exclusive": false,
            "no_wait": true,
            "mandatory": true,
            "immediate": false
          }
        }
```

**Comment by alombarte** [comment]
Related https://github.com/krakendio/krakend-ce/issues/486

**Comment by taik0** [comment]
An automatic connection retry is added in #18
